--
-- PostgreSQL database dump
--

\restrict jIhUBvhusTAD4ADfxs8fiw3y1hwdb19qMRoRshX3qLtRBYgkEUaq5dqVwWpnCy0

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: curso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.curso (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    cant_creditos integer,
    profesor_id integer,
    cupo_max integer,
    CONSTRAINT curso_cant_creditos_check CHECK ((cant_creditos > 0)),
    CONSTRAINT curso_cupo_max_check CHECK ((cupo_max > 0))
);


--
-- Name: curso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.curso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estudiante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estudiante (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    correo character varying(100) NOT NULL,
    carrera character varying(50) NOT NULL,
    semestre_actual integer,
    fecha_ingreso timestamp without time zone DEFAULT '2026-06-24 20:38:18.505697'::timestamp without time zone,
    estado character varying(50) DEFAULT 'activo'::character varying,
    CONSTRAINT estudiante_estado_check CHECK (((estado)::text = ANY ((ARRAY['activo'::character varying, 'inactivo'::character varying])::text[]))),
    CONSTRAINT estudiante_semestre_actual_check CHECK (((semestre_actual >= 1) AND (semestre_actual <= 10)))
);


--
-- Name: estudiante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estudiante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estudiante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inscripcion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inscripcion (
    id integer NOT NULL,
    fecha_ins timestamp without time zone DEFAULT '2026-06-24 20:38:18.610229'::timestamp without time zone,
    estado character varying(50) DEFAULT 'activo'::character varying,
    estudiante_id integer,
    curso_id integer,
    CONSTRAINT check_estado_inscripcion CHECK (((estado)::text = ANY ((ARRAY['activa'::character varying, 'aprobada'::character varying, 'reprobada'::character varying])::text[])))
);


--
-- Name: inscripcion_clonebk; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inscripcion_clonebk (
    id integer,
    fecha_ins timestamp without time zone,
    estado character varying(50),
    estudiante_id integer,
    curso_id integer
);


--
-- Name: inscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nota (
    id integer NOT NULL,
    tipo_evaluacion character varying(50),
    valor_nota integer,
    fecha timestamp without time zone DEFAULT '2026-06-24 20:38:18.616263'::timestamp without time zone,
    inscripcion_id integer,
    CONSTRAINT nota_valor_nota_check CHECK (((valor_nota >= 0) AND (valor_nota <= 100)))
);


--
-- Name: nota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profesor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profesor (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    correo character varying(100) NOT NULL,
    departamento character varying(50) NOT NULL,
    fecha_contratacion timestamp without time zone DEFAULT '2026-06-24 20:38:18.569133'::timestamp without time zone
);


--
-- Name: profesor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profesor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profesor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id);


--
-- Name: estudiante estudiante_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT estudiante_correo_key UNIQUE (correo);


--
-- Name: estudiante estudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT estudiante_pkey PRIMARY KEY (id);


--
-- Name: inscripcion inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT inscripcion_pkey PRIMARY KEY (id);


--
-- Name: nota nota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota
    ADD CONSTRAINT nota_pkey PRIMARY KEY (id);


--
-- Name: profesor profesor_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_correo_key UNIQUE (correo);


--
-- Name: profesor profesor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_pkey PRIMARY KEY (id);


--
-- Name: inscripcion_curso_id_estudiante_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX inscripcion_curso_id_estudiante_id_idx ON public.inscripcion USING btree (curso_id, estudiante_id);


--
-- Name: curso curso_profesor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_profesor_id_fkey FOREIGN KEY (profesor_id) REFERENCES public.profesor(id) DEFERRABLE;


--
-- Name: inscripcion inscripcion_curso_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT inscripcion_curso_id_fkey FOREIGN KEY (curso_id) REFERENCES public.curso(id) DEFERRABLE;


--
-- Name: inscripcion inscripcion_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT inscripcion_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiante(id) DEFERRABLE;


--
-- Name: nota nota_inscripcion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota
    ADD CONSTRAINT nota_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES public.inscripcion(id) DEFERRABLE;


--
-- PostgreSQL database dump complete
--

\unrestrict jIhUBvhusTAD4ADfxs8fiw3y1hwdb19qMRoRshX3qLtRBYgkEUaq5dqVwWpnCy0

