### Probar servidor
GET http://localhost:3000/

###

### Probar conexión a PostgreSQL
GET http://localhost:3000/test-db

###

### Ver tablas
GET http://localhost:3000/tablas

###

### Listar estudiantes
GET http://localhost:3000/api/estudiantes

###

### Obtener estudiante por ID
GET http://localhost:3000/api/estudiantes/1

###

### Listar profesores
GET http://localhost:3000/api/profesores

###

### Obtener profesor por ID
GET http://localhost:3000/api/profesores/1

###

### Crear estudiante
POST http://localhost:3000/api/estudiantes
Content-Type: application/json

{
  "nombre": "Santiago Gutierrez",
  "correo": "santiago@gmail.com",
  "carrera": "Ingenieria de Sistemas",
  "semestre_actual": 4
}

### ACTUALIZAR ESTUDIANTE
PUT http://localhost:3000/api/estudiantes/1
Content-Type: application/json

{
  "nombre": "Martin Serrano",
  "correo": "martin@gmail.com",
  "carrera": "Ingeniería de Sistemas",
  "semestre_actual": 5
}

### Actualizar profesor
PUT http://localhost:3000/api/profesores/1
Content-Type: application/json

{
  "nombre": "Carlos Pérez",
  "correo": "carlos.perez@universidad.edu",
  "departamento": "Ingeniería de Sistemas"
}

### Actualizar curso
PUT http://localhost:3000/api/cursos/1
Content-Type: application/json

{
  "nombre": "Base de Datos para Cracks",
  "cant_creditos": 4,
  "profesor_id": 2,
  "cupo_max": 40
}